[probe]
aolda-probe ansible_host=lima-aolda-probe

[probe:vars]
ansible_connection=ssh
ansible_ssh_common_args='-F /Users/jjjjjk12/.lima/aolda-probe/ssh.config'
ansible_python_interpreter=/usr/bin/python3
