keycloak_host: keycloak.jinkang.dev
kube_prometheus_stack_alertmanager_host: alertmanager.jinkang.dev
kube_prometheus_stack_grafana_host: grafana.jinkang.dev
kube_prometheus_stack_prometheus_host: prometheus.jinkang.dev
openstack_helm_endpoints_barbican_api_host: key-manager.jinkang.dev
openstack_helm_endpoints_cinder_api_host: volume.jinkang.dev
openstack_helm_endpoints_designate_api_host: dns.jinkang.dev
openstack_helm_endpoints_glance_api_host: image.jinkang.dev
openstack_helm_endpoints_heat_api_host: orchestration.jinkang.dev
openstack_helm_endpoints_heat_cfn_api_host: cloudformation.jinkang.dev
openstack_helm_endpoints_horizon_api_host: dashboard.jinkang.dev
openstack_helm_endpoints_ironic_api_host: baremetal.jinkang.dev
openstack_helm_endpoints_keystone_api_host: identity.jinkang.dev
openstack_helm_endpoints_magnum_api_host: container-infra.jinkang.dev
openstack_helm_endpoints_magnum_registry_host: container-infra-registry.jinkang.dev
openstack_helm_endpoints_manila_api_host: share.jinkang.dev
openstack_helm_endpoints_neutron_api_host: network.jinkang.dev
openstack_helm_endpoints_nova_api_host: compute.jinkang.dev
openstack_helm_endpoints_nova_novnc_host: vnc.jinkang.dev
openstack_helm_endpoints_octavia_api_host: load-balancer.jinkang.dev
openstack_helm_endpoints_placement_api_host: placement.jinkang.dev
openstack_helm_endpoints_region_name: RegionOne
openstack_helm_endpoints_rgw_host: object-store.jinkang.dev
